#!/usr/bin/env ruby
# encoding: UTF-8

require 'mechanize'

##### Configuration

KOKOKOZA_URL = 'http://www.nhk.or.jp/kokokoza/library/index_2011.html'

##### Classes

class Kokokoza < Mechanize
  def videos
    get(KOKOKOZA_URL).links_with(:href => %r{/tv/}).each do |link|
      handle_section(link)
    end
  end

private

  def handle_section(link)
    transact {
      section_name = link.text
      link.click
      handle_section_tab(section_name)

      page.links_with(:href => %r{^index\d+\.html}).each do |link|
        link.click
        handle_section_tab(section_name)
      end
    }
  end

  def handle_section_tab(section_name)
    page.links.each do |link|
      if link.href =~ %r{/chapter(\d+).html}
        handle_video(section_name, $1.to_i, link)
      end
    end
  end

  def handle_video(section_name, episode, link)
    transact {
      # the following regexp comes from http://www.ruby-forum.com/topic/860528
      video_name = link.text.sub(/\A[[:space:]]*(.*?)[[:space:]]*\z/, '\1')
      link.click
      puts section_name, '%02d - %s' % [episode, video_name],
           page.link_with(:href => /\.asx$/).href, ''
    }
  end
end

##### Main program

Kokokoza.new.videos
