#!/usr/bin/env ruby
# encoding: UTF-8

require 'mechanize'
require 'set'

##### Configuration

KOKOKOZA_URL = 'http://www.nhk.or.jp/kokokoza/library/index.html'

##### Classes

class Kokokoza < Mechanize
  def videos
    get(KOKOKOZA_URL).links_with(:href => %r{^tv/}).each do |link|
      handle_section(link)
    end
  end

private

  def handle_section(link)
    if OPT_DEBUG
      STDERR.puts "Section: #{link.uri}"
    end
    transact {
      section_name = link.text
      link.click

      visited_episodes = Set.new
      page.links.each do |link|
        if link.href =~ %r{/chapter(\d+).html}
          episode = $1.to_i
          unless visited_episodes.include?(episode)
            handle_video(section_name, episode, link)
            visited_episodes << episode
          end
        end
      end
    }
  end

  def handle_video(section_name, episode, link)
    if OPT_DEBUG
      STDERR.puts "Video page: #{link.uri}"
    end
    transact {
      # the following regexp comes from http://www.ruby-forum.com/topic/860528
      video_name = link.text.sub(/\A[[:space:]]*(.*?)[[:space:]]*\z/, '\1')
      link.click
      if video_link = page.link_with(:href => /\.asx$/)
        puts section_name, '%02d - %s' % [episode, video_name],
             video_link.href, ''
      end
    }
  end
end

##### Argument parsing

OPT_DEBUG = ARGV[0] == '--debug' && ARGV.shift
if ARGV.size > 0
  abort "Usage: #$0 [--debug]"
end

##### Main program

Kokokoza.new.videos
