#!/usr/bin/env ruby
# encoding: UTF-8

require 'fileutils'

##### Configuration

VIDEO_EXTENSION = '.wmv'

##### Argument parsing

DEST_DIR = ARGV[0]
if DEST_DIR.nil? or not File.directory?(DEST_DIR)
  STDERR.puts "Usage: #$0 <destination directory>"
  exit 1
end

##### Main program

saved_section, counter = nil, nil

STDIN.collect { |line| line.chomp }
     .chunk { |line| (not line.empty?) || nil }
     .each do |_, lines|
  section, video, url = lines
  streaming_url =
      url.sub(%r{^http://www}, 'mms://wm')
         .sub('/kokokoza/metafiles/', '/wm2/kokokoza-mov/streaming/')
         .sub(/\.asx$/, VIDEO_EXTENSION)

  if section != saved_section
    saved_section = section
    counter = 0
  end
  counter += 1

  dest_dir = File.join(DEST_DIR, section.gsub('/', '／'))
  dest_file = File.join(dest_dir,
                        '%02d - %s' % [counter, video + VIDEO_EXTENSION])
  unless File.exists?(dest_file)
    FileUtils.mkdir_p(dest_dir)
    unless system('mimms', '--quiet', streaming_url, dest_file)
      exit 1
    end
  end
end
